name: myflutterapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  http: ^0.13.3         
  uuid: ^4.5.1          
  material_color_utilities: ^0.11.1  
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  
